name: snapmanager
base: core24
version: '1.1'
summary: DIWhy flatseal for snap, using Gum
description: |
  DIWhy flatseal for flatpak, using Gum

grade: stable
confinement: classic

apps:
  snapmanager:
    command: usr/bin/snapmanager
    environment:
      PATH: "$SNAP/usr/bin:$PATH"
    plugs:
      - home

parts:
  snapmanager:
    source: .
    plugin: dump
    organize:
      snapmanager.sh: usr/bin/snapmanager
      gum: usr/bin/gum